### ISSUE TITLE
onPictureTaken not properly documented

### ISSUE THREAD

**Issue by krischik** [doo/Scanbot-SDK-Documentation#1]
The current documentation of onPictureTaken reads:

```
 void onPictureTaken(byte[] image,
                     int imageOrientation)
 Invoked when picture is taken
```

That leaves one guessing which values imageOrientation can take — or why imageOrientation is not an enum.

**Comment by dmitry-zaitsev** [comment]
Good point, thanks. We'll update the documentation and argument name.

`imageOrientation` takes values between 0 and 360 which represent degree by which image is rotated relatively to what you see on camera stream.

**Comment by krischik** [comment]
Thanks. I guess it not what I am need then. Trying to rotate the picture into portrait when it is landscape and was wondering if the parameter holds a usable hint.

**Comment by dmitry-zaitsev** [comment]
The whole point of this `imageOrientation` parameter is that `image` which we receive from camera has the same rotation as hardware camera sensor (which, of course, varies from device to device). In order to compensate that we need this parameter.

> Trying to rotate the picture into portrait when it is landscape 

Could you please explain your use case a bit more? Not sure I understood the problem.

**Comment by eddyfrank** [comment]
We haven't received a response to this issue and are assuming that this is solved.
